### ISSUE TITLE
Incompatible Protocol Version

### ISSUE THREAD

**Issue by ghost** [DyKnow/SignalR-ObjC#121]
Hi,

Today i have upgrade my Server Side to Version SignalR 1.0.0-rc2, and i have upgrade my iOS Client using cocoapods from the terminal it's said this is the latest version
Using SignalR-ObjC (1.0.alpha2)

I Run my ios client it's unable to link to my server and encounter "Incompatible Protocol Version" any news when it's support 1.0.0-rc2?

Thanks

**Comment by TheRoot10** [comment]
Hi abillingsley,

I am using SignalR version 1.0.1. SignalR connection is starting successfully, But some times i am receiving data and some time i am not receiving data from server (connection.received method is not getting called). Please check the ios code below.

SRHubConnection *connection = [SRHubConnection connectionWithURL:@"http://strandd-dev.azure-mobile.net/signalr"];
connection.delegate = self;
[connection addValue:token forHTTPHeaderField:@"X-ZUMO-AUTH"];
[connection addValue:@"Basic REVWOnZPdGZOVHBnYlNxZ3RtZFZ2VENLVGVYTkxvek9CeDE2" forHTTPHeaderField:@"Authorization"];
myHub = [connection createHubProxy:@"IncidentHub"];
connection.error = ^(NSError *error){
        NSLog(@"error ====%@",error);
};
connection.started = ^{
        NSLog(@"Connection Started");
        [myHub invoke:@"GetMobileCustomerClientIncidentStatusRequest" withArgs:[NSArray arrayWithObjects:incidentGUID, nil]];
        [self.delegate signalrConnectionDidStarted];
};
connection.received = ^(NSString * data){
        NSLog(@"data ====%@",data);
        [self.delegate didReceivedDataFromSignalR:data];
};
[connection start];

Can you please help me to find out this issue.

**Comment by aman-saggu-git** [comment]
hello guys i am also getting same type of error i my case .below is some glimpse of my error log- 

2016-11-09 21:18:06.998 iOS Example[5914:164218] CONNECTION:    will negotiate
2016-11-09 21:18:07.051 iOS Example[5914:164218] AUTO:  autoTransport will negotiate
2016-11-09 21:18:09.442 iOS Example[5914:164218] TRANSPORT: will negotiate at url: ## **http://14.140.162.29:8057/signalr/signalr/negotiate?clientProtocol=1.3.0.0&connectionData=%5B%7B%22Name%22%3A%22mychathub%22%7D%5D**

**after some time below code appear in output windows in error log and app building stops -** 

2016-11-09 21:19:30.371 iOS Example[5914:164218] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Incompatible Protocol Version'

signalr library in my asp.net solution is having below versions as per package.config
 <package id="Microsoft.AspNet.SignalR" version="1.0.0-rc1" targetFramework="net40" />
  <package id="Microsoft.AspNet.SignalR.Core" version="1.0.0-rc1" targetFramework="net40" />
  <package id="Microsoft.AspNet.SignalR.JS" version="1.0.0-rc1" targetFramework="net40" />
  <package id="Microsoft.AspNet.SignalR.Owin" version="1.0.0-rc1" targetFramework="net40" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="1.0.0-rc1" targetFramework="net40" />

but you can protocol version in 1.3.0.0 in url above provided that came  in output windows while debugging ios app how can i get this error fix . some details will be highly appreciated
